Fix bug in deploy --resume
AttributeError: 'Environment' object has no attribute 'deploy_env'

The error was always swallowed by `except Exception`, which made it impossible to resume a deploy that way.