Fix /opt/data permissions on Vagrant
Disable ecryptfs environment because ES and Kafka fail to start:

ecryptfs can't mmap shared libraries with exec permission, so JNA
fails to load its native library out of /opt/data, which then makes
ES's seccomp/system-call-filter bootstrap check fail and abort startup

[WARN ][o.e.b.Natives] [es0] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /opt/data/elasticsearch-6.8.23/tmp/jna8792826677444915978.tmp:
/opt/data/elasticsearch-6.8.23/tmp/jna8792826677444915978.tmp: failed to map segment from shared object
...
[INFO ][o.e.e.NodeEnvironment] [es0] using [1] data paths, mounts [[/opt/data (/opt/data)]], ..., types [ecryptfs]