Ssh server is required
Previously ssh without a server caused a traceback with an unhelpful error:
TypeError: expected string or bytes-like object

Lookup's server has nargs="?", which makes the argument optional. This
is valid for Lookup, but not for _Ssh and its subclasses.