Fix check-mode missing sql_file_path.dest
Error: The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dest'

The error appears to be in 'src/commcare_cloud/ansible/roles/pg_repack/tasks/main.yml': line 66, column 5, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Run queries from SQL script
    ^ here